##############################################################################################
# Youtuber, change the "name1, name2, etc" to whatever name you want for your youtubers list #
##############################################################################################
youtube:
  - name1
  - name2
  - name3
  - name4
  - name5

##############################################################################################
# Twitcher, Same thing has youtuber just put there twitch names in it                        #
##############################################################################################
twitch:
  - name1
  - name2
  - name3
  - name4
  - name5