name: Youtuber
author: TrpkGod
version: 1.7.7
description: Youtuber Plugin
main: TrpkGod.Youtuber.Youtuber
commands:
  Youtuber:
    description: Shows a list of commands.
  Youtube:
    description: Base command for any youtube commands.
  Twitch:
    description: Base command for any twitch commands.
  Api:
    description: Base command for any youtube or twitch api commands.