name: Youtuber
author: TrpkGod
version: 1.8.9
description: Youtuber Plugin
main: TrpkGod.Youtuber.Youtuber
commands:
  Youtuber:
    usage: /<command> <args>
    description: Base command for the plugin.
  Youtube:
    usage: /<command> <args>
    description: Base command for Youtube.
  Twitch:
    usage: /<command> <args>
    description: Base command for Twitch.